[package]
name = "midproxy"
version = "0.1.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "A cli tool to proxy and analyze HTTP/HTTPS"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/midproxy"
repository = "https://github.com/sigoden/midproxy"
categories = ["command-line-utilities"]
keywords = ["proxy", "mitm"]

[dependencies]
anyhow = "1.0"
bytes = "1.5"
clap = { version = "4.5.1", features = ["derive"] }
hexplay = "0.3.0"
http-body-util = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "fs", "io-util", "signal"]}
tokio-util = { version = "0.7",  features = ["io-util", "compat"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["server-auto", "client-legacy"] }
hyper-tls = "0.6.0"
socket2 = "0.5.6"
async-compression = { version = "0.4.6", features = ["brotli", "gzip", "deflate", "tokio"] }

[profile.release]
lto = true
strip = true
opt-level = "z"